### ISSUE TITLE
Voip credentials with latest firmware

### ISSUE THREAD

**Issue by Xandrios** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#3]
Hi there,

Thanks for the work into this project. I managed to get the API to work by simply logging in to the model (using the browser), capturing the Ajax-http-call, and repeating that call with the endpoints listed in your overview. That worked very well.

However...the VOIP credentials are indeed not being returned as I am on 09022001.00.030_OTE5. The solution for this, firmware downgrade, is a bit of a risky one...I am a little hesitant as I would not want to brick my modem. 

Ive been looking into decrypting the downloaded/saved config file. Theoretically this file should also contain all information. There are a bunch of scripts out there that are supposed to be able to do this... but I have not been able to get proper output from these. The decryption seems to fail somehow.

Have you been able to decrypt a saved config? 

Reason for wanting the VOIP credentials is that I'd like to experiment with using a SIP phone app. My Cosmote modem has been very unstable, and the Cosmote guys have replaced it and even come down to test the line. They couldnt find any issues. Yet whenever it has rained the connection drops every 30 minutes. So I'm thinking to use an alternative modem (Asus) but those don't have Voip ports.. hence the need to be able to handle the Voice calls another way.

**Comment by Notupus** [comment]
Hello @Xandrios ,
I personally made the pull request for the firmware downgrade. I initially wanted to just link cosmote's site for an older software version of the firmware but I did not want to run the risk of cosmote just removing it from their site.  As far I've tested on mine and 6 other routers there is no risk downgrading from 09022001.00.030_OTE5.img but cosmote has been upgrading the Speedport plus routers to 09022001.00.031_OTE1 gradually through TR-69. If you think there is a risk you can downgrade to https://help.cosmote.gr/system/templates/selfservice/gnosisgr/files2/09022001.00.030_OTE5.img first and then go back but as far as I see all that has changed is the dsl modem firmware. On the topic of decrypting the configuration file it seems to have a lot of entropy so I don't think we will be able to get it decrypted if we don't have the JFFS2 filesystem of the device itself, which would either require specialized tools or a hot air station to de solder it and read it(destroying it in the process potentially). The serial output of the device does dump some info on the voip settings like phone number but the password seems either omitted or hashed. Your line problem is likely the ote distribution box since those are often not sealed and get moist when it rains significantly reducing SNR. There has been no tool that can decode either the firmware file or the config file so all we have is these requests. Also you might be able to get tr-69 access if you setup a server and use a custom dns that points to that but I have no idea if that works.

**Comment by Notupus** [comment]
Here is the firmware link from cosmote if you want to check hashes  https://help.cosmote.gr/system/templates/selfservice/gnosisgr/files2/09022001_00_021.img
