### ISSUE TITLE
.img given is not accepted for downgrading

### ISSUE THREAD

**Issue by bariemai666** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#8]
Kalispera :) The 09022001_00_021.img is not accepted as a valid firmware for downgrading.
https://help.cosmote.gr/system/templates/selfservice/gnosisgr/files2/09022001_00_021.img
you can add this link for a fresh download of the .img. 
The get_data worked like a charm.
Million thanks <3

**Comment by nikolas-n** [comment]
Hello,

I downloaded the file you are linking and it is exactly the same as the one in the repo (checked with diff). Most likely, since it's a LFS file, you hadn't downloaded it properly. I've added a comment in the relevant section of the repo regarding that.

Great that the get_data worked for you, you're welcome!
